### ISSUE TITLE
Setting custom fields on a signature request fails

### ISSUE THREAD

**Issue by lenniboy** [techblue/docusign-restclient#22]
I'm trying to add custom fields to a signature request but instead I get the following error:

```
 uk.co.techblue.docusign.client.exception.SignatureRequestException: Request processing failed. HTTP Status: 400
Error:ErrorResponse[errorCode=INVALID_REQUEST_BODY,message=The request body is missing or improperly formatted. Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'API_REST.Models.v2.customFields' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path 'customFields', line 1, position 567.]
```

So, Docusign cannot parse the JSON that the client sends. The HTTP client logs the JSON as the following:

```
{
  "emailBlurb": "Please sign the document.",
  "emailSubject": "Please sign attached document",
  "status": "sent",
  "recipients": {
    "signers": [
      {
        "recipientId": "1",
        "email": "foo@bar.com",
        "name": "John Doe",
        "tabs": {
          "signHereTabs": [
            {
              "documentId": "1",
              "xPosition": 72,
              "yPosition": 250,
              "pageNumber": 1
            }
          ]
        }
      }
    ]
  },
  "documents": [
    {
      "documentId": "1",
      "name": "monoqi-MQ-123.pdf"
    }
  ],
  "customFields": [
    {
      "customFieldType": "text",
      "name": "id",
      "value": "MQ-123"
    },
    {
      "customFieldType": "text",
      "name": "documentType",
      "value": "pdf"
    }
  ]
}
```

It isn't entirely clear from the [documentation](https://www.docusign.com/p/RESTAPIGuide/RESTAPIGuide.htm#REST API References/Send an Envelope.htm%3FTocPath%3DREST%2520API%2520References%7CSend%2520an%2520Envelope%2520or%2520Create%2520a%2520Draft%2520Envelope%7C_____0) but I think the JSON content of the `customFields` attribute should be something like this:
```
{
  "listCustomFields":[{
    "fieldId": "String content",
    "name": "String content",
    "required": "String content",
    "show": "String content",
    "value":"String content",
    "listItems":["String content"]
  }]
  "textCustomFields":[{
    "fieldId": "String content",
    "name": "String content",
    "required": "String content",
    "show": "String content",
    "value":"String content"
  }]
}
```
What do you think?

**Comment by dheerajarora** [comment]
This seems to be a bug in the rest client. I own this issue and fix it.

**Comment by lenniboy** [comment]
Fantastic! Thanks for the quick reply.

**Comment by dheerajarora** [comment]
It has been fixed. Give it a try and let me know if you face any other issue.

**Comment by lenniboy** [comment]
Thanks a lot! It works great but I have a small request. The code seems to produce two JSON properties: `customFields` and `CustomFields` (with a capital C). This isn't the end of the world but that means when I receive the callback from DocuSign, the custom fields are returned twice. 

I think the offending Java variable is this one: https://github.com/techblue/docusign-restclient/commit/3003b982cf76f30194ca1b530290512a88678d31#diff-ffe98fb8908c5c69040be5fe702a101eR45

**Comment by lenniboy** [comment]
And if you want to make me even more happy, you'd push a release to Maven central, too.

**Comment by dheerajarora** [comment]
Sure. I'd make you happy by pushing release to Maven central. ;) 
There is some more code which also beeds to be merged and then I'll release it.

**Comment by RossMackie** [comment]
@ajaydeshwal Hello there I was wondering if this ever got published to maven? As I couldn't see the updated code and I am getting this issue.

**Comment by PavanKumarH** [comment]
@dheerajarora Hello, Is this issue resolved in maven using spring boot? I am still getting the same error if I send the Json string as Post request Body.
