### ISSUE TITLE
Radio group locked field

### ISSUE THREAD

**Issue by jonathan-chen-tda** [techblue/docusign-restclient#23]
In the DocuSign v2 API docs, it seems there is a setting for Radio Group Tab and Radio Button for locking the field. I am not seeing that field in restclient 2.0.4, only templateLocked. Is there a reason why this is missing?

**Comment by dheerajarora** [comment]
There is not any specific reason for that. Initially we developed this Rest client for v1 version of Docusign. Later when DocuSign release v2 version of Rest API, so we migrated only the parts which were required not as a whole API.

**Comment by dheerajarora** [comment]
Thanks for raising this issue. Initially we developed this Rest client for v1 version of Docusign. Later when DocuSign release v2 version of Rest API, we migrated only the parts which were required not the whole API. This particular property for Radio Button was also introduced in V2.

I'll add locked property and other available properties as well on the master branch.

**Comment by dheerajarora** [comment]
Done. Added locked property for Radio Button.

**Comment by jonathan-chen-tda** [comment]
Thanks!
