### ISSUE TITLE
Connections aren't released

### ISSUE THREAD

**Issue by ulischulte** [techblue/docusign-restclient#24]
While using the EnvelopeService I ran into some problems regarding unclosed Connections. Generally all methods using the resourceProxy don't release the connections which might lead to 'Invalid use of BasicClientConnManager: connection still allocated'. A way to solve this problem would be placing the following statement after each call on the resourceProxy:

`clientResponse.releaseConnection();`

**Comment by dheerajarora** [comment]
I've merged your pull request. Thanks for the contribution.
